version: '3.4'

volumes:
  db_volume:
    name: db_volume
networks:
  GE:
    external:
      name: nat
services:
  db:
    image: postgres
    container_name: Ocetya.PeopleCounter.DB
    environment:
      POSTGRES_USER: "geadmin"
      POSTGRES_PASSWORD: "Th1sIs4Pa5sw0rd"
      POSTGRES_DB: "CamerasDB"
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - GE
  ocetya.peoplecounter.service:
    image: ${DOCKER_REGISTRY-}ocetyapeoplecounterservice
    depends_on:
      - db
    build:
      context: .
      dockerfile: Ocetya.PeopleCounter.Service\Dockerfile
    networks:
      - GE
  ocetya.peoplecounter.web:
    image: ${DOCKER_REGISTRY-}ocetyapeoplecounterweb
    depends_on:
      - db
    build:
      context: .
      dockerfile: Ocetya.PeopleCounter.Web\Dockerfile
    ports:
      - "8080:80"
      - "8000:443"
    networks:
      - GE