// <auto-generated />
using System;
using GranEstacion.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GranEstacion.Repository.Migrations
{
    [DbContext(typeof(GranEstacionContext))]
    [Migration("20200723222800_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("GranEstacion.Repository.Camera", b =>
                {
                    b.Property<int>("CameraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("CameraId");

                    b.ToTable("Cameras");

                    b.HasData(
                        new
                        {
                            CameraId = 1,
                            Name = "Subida Rampa de Sotano 2 a Sotano 1"
                        },
                        new
                        {
                            CameraId = 2,
                            Name = "Salida Ascensor Sotano 1"
                        },
                        new
                        {
                            CameraId = 3,
                            Name = "Subida Escaleras Sotano 1 a Piso 1"
                        },
                        new
                        {
                            CameraId = 4,
                            Name = "Rampa Subida Sotano 1 a Piso 1"
                        },
                        new
                        {
                            CameraId = 5,
                            Name = "Rampa Bajada de Piso 1 a Sotano 1"
                        },
                        new
                        {
                            CameraId = 6,
                            Name = "Tunel Granestacion 1-2"
                        },
                        new
                        {
                            CameraId = 7,
                            Name = "Puerta 2 Costado Norte"
                        },
                        new
                        {
                            CameraId = 8,
                            Name = "Puerta 2 Costado Sur"
                        },
                        new
                        {
                            CameraId = 9,
                            Name = "Puerta 1 Costado Norte"
                        },
                        new
                        {
                            CameraId = 10,
                            Name = "Puerta 1 Costado Sur"
                        },
                        new
                        {
                            CameraId = 11,
                            Name = "Salida Ascensor Sotano 2"
                        },
                        new
                        {
                            CameraId = 12,
                            Name = "Bajada a Rampa a Sotano 2"
                        });
                });

            modelBuilder.Entity("GranEstacion.Repository.Log", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CameraId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Entered")
                        .HasColumnType("integer");

                    b.Property<int>("Exited")
                        .HasColumnType("integer");

                    b.HasKey("LogId");

                    b.HasIndex("CameraId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("GranEstacion.Repository.Log", b =>
                {
                    b.HasOne("GranEstacion.Repository.Camera", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
